### ISSUE TITLE
This script is a scam, read the code.  It sent my coins to "mole"  beware.

### ISSUE THREAD

**Issue by manureek** [Aareksio/csgodoubled-automated#3]
This isnt cool man.  Leading people onto something like this just to steal their coins.  Lucky when i ran this program the other day it didnt send you my 100+$ i had, but i got 7$ today from a friend, and well, you changed your script, which i should have seen and it sent you(Mole) my coins.  If you have a heart, please send back to me?  76561198068862049 is my id.  you took 7371.  please send back to me?  i did like your script when i ran it the first time, i didnt make much because i was scared.  but ty in advance if you send the coins.   gg

**Comment by Aareksio** [comment]
https://github.com/Aareksio/csgodoubled-automated/blob/master/csgodouble.com-automated.user.js#L224
