### ISSUE TITLE
License does not cover send code hosted on website.

### ISSUE THREAD

**Issue by jmeyer2k** [Aareksio/csgodoubled-automated#8]
Send me my coins or I'll take this to court. This is your last chance.

**Comment by Aareksio** [comment]
The license covers the whole program...

**Comment by jmeyer2k** [comment]
The license covers everything hosted on github. You are liable for the code
hosted on your website.

**Comment by Aareksio** [comment]
It's a part of the project, you were aware of it the moment you decided to use the code, also - everything on this domain is available under MIT license as well. You didn't have to use this, it's free to use, but on your own responsibility.
